project:
  type: book
  output-dir: docs

book:
  title: "Modern Investments: Theory, Data, and Practice"
  author: "Kerry Back, Barbara Bennett, Kevin Crotty, and Yuhang Xing"
  date: "8/18/2022"
  chapters:
    - index.qmd
    - miracle.qmd
    - portfolios.qmd
    - input_sensitivity.qmd
    

format:
  html:
    theme: cosmo
    code-fold: true


