project:
  type: book
  output-dir: docs

book:
  title: "Modern Investments: Theory, Data, and Practice"
  author: "Kerry Back, Barbara Bennett, Kevin Crotty, and Yuhang Xing"
  date: "9/27/2022"
  chapters:
    - index.qmd
    - miracle.qmd
    

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  freeze: auto

