project:
  type: book
  output-dir: docs

book:
  title: "Modern Investments: Theory, Data, and Practice"
  author: "Kerry Back, Barbara Bennett, Kevin Crotty, and Yuhang Xing"
  date: "1/1/2023"
  chapters:
    - index.qmd
    - miracle.qmd
    - diversification.qmd
    - portfolios.qmd
    - portfolios_frictions.qmd
    

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: Chapter contents

execute:
  freeze: auto
  echo: false

fig-cap-location: top

comments:
  hypothesis: true
  giscus:
    repo: bbcx-investments/publish

