project:
  type: book
  output-dir: docs

book:
  title: "Modern Investments: Theory, Data, and Practice"
  author: "Kerry Back, Barbara Bennett, Kevin Crotty, and Yuhang Xing"
  date: "9/27/2022"
  chapters:
    - index.qmd
    - miracle.qmd
    - diversification.qmd
    - portfolios.qmd
    - portfolios_frictions.qmd
    - fixed-income.qmd
    

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    toc-depth: 2
    
execute:
  freeze: auto

comments:
  giscus:
    repo: bbcx-investments/publish

