project:
  type: book

book:
  title: "Modern Investments: Theory, Data, and Practice"
  author: "Kerry Back, Barbara Bennett, Kevin Crotty, and Yuhang Xing"
  date: "8/18/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    self-contained: true
  pdf:
    documentclass: scrreprt



