

# Miracle of Compound Interest

If an investment account earns a steady rate of return and funds are not withdrawn from the account, then the account balance will grow exponentially.  This is sometimes called the "miracle of compound interest."  @fig-miracle-exponential shows the growth of an investment account earning 8% per year, which is what the U.S. stock market earned in real terms over the thirty year period 1992-2021.  Each dollar grows to roughly $10 over a 30 year period at an 8% annual return.  The exponential nature of the growth can be seen from the figure.  Hover over the plot to see the exact values.

```{python}
#| label: fig-miracle-exponential
#| fig-cap: "Growth of an Investment Account"


import plotly.graph_objects as go
import numpy as np

trace1= go.Scatter(
    x=np.arange(31), 
    y=1.08**np.arange(31),
    mode="lines",
    name="8%"
)

trace2 = go.Scatter(
    x=np.arange(31), 
    y=1.04**np.arange(31),
    mode="lines",
    name="4%"
)

fig = go.Figure()
fig.layout.template = "none"
fig.add_trace(trace1)
fig.add_trace(trace2)
fig.update_traces(
    hovertemplate="""
    Year %{x}<br>
    $%{y:.2f}<extra></extra>
    """
)
fig.layout.xaxis["title"] = "Year"
fig.layout.yaxis["title"] = "Account Balance"
fig.update_layout(
    yaxis_tickprefix="$", 
    yaxis_tickformat=",.0f",
    legend=dict(
        yanchor="top", 
        y=0.99, 
        xanchor="left", 
        x=0.01
        )
)
fig.show()
```

Investments grow exponentially because they earn returns each year not just on the starting balance but also on all prior returns.  Exponential growth is much better than linear growth.  By "linear growth," we mean that doubling the investment period would double the account growth.  Exponential is much better than that.  As can be seen from the figure, $1 would grow to slightly more than $3 in 15 years at 8% per year, so the growth in value is slightly more than $2.  Doubling the investment horizon to 30 years increases the growth to $9 (from $1 to $10), so the growth in value is more than four times larger when the horizon doubles, with an 8% return.   Because of exponential growth, it is incredibly important to invest early and to refrain from borrowing whenever possible (unless the borrowing finances the purchase of long-term assets).

Exponential growth also means that the rate of return one earns is extremely important.  For example, one might think that earning 8% is twice as good as earning 4%, but that is an understatement.  Over a 30 year period, earning 8% is more than four times as good as earning 4%---a dollar grows by $9 to $10 over 30 years at 8%, but it grows by less than $2.25 at 4%.

The values in @fig-miracle-exponential are calculated from the following logic.  $1 invested for 1 year at 8% grows to $1.08.  After another year at 8%, we have 
\begin{align*}
1.08 + (0.08 \times 1.08) &= (1.08 \times 1) + (1.08 \times 0.08)\\ &  = 1.08 \times 1.08 \\ &= 1.08^2
\end{align*}
Continuing with this logic, we can see that after $n$ years, we have $1.08^n$.  Thus, the number of years is the exponent of the factor 1.08, which is the definition of exponential growth.

As remarked above, the exponential growth is due to earning returns on top of returns or "interest on interest."  After two years at 8%, we have
$$1.08^2 = 1 + 0.08 + 0.08 + (0.08\times 0.08).$$  Linear growth would be just adding up the returns $0.08 + 0.08$.  Exponential growth is due to the "interest on interest" term $0.08 \times 0.08.$  This is a small number when there are only two years, but these terms add up to a very large number over many years.  They are responsible for the growth in the investment account quadrupling (from $2.17 to $9.06) when the investment horizon is doubled (from 15 to 30 years) with 8% returns.

## Future values and present values

We call $1.08^n$ the future value of $1 for an $n$-year horizon and 8\% returns.  We can write this more generally as $(1+r)^n$, where $r$ is the rate of return (0.08 in our example).  The future value $(1+r)^n$ is what \\$1 grows to in $n$ years when the rate of return is $r$.  

We also call $1 the present value of $(1+r)^n$.  It is how much you need to invest to reach $(1+r)^n$ in $n$ years when the rate of return is $r$.  More generally, we call [$x$ the present value of $y$]{style="color: Tomato;"}, and we call [$y$ the future value of $x$]{style="color: Tomato;"} when $x$ and $y$ are related as 
$$y=x(1+r)^n,$$ because $x$ will grow to $y$ in $n$ years when the rate of return is $r$.  We compute the future value $y$ from the present value $x$ by mutliplying $x$ by $(1+r)^n$, so we call $(1+r)^n$ the [future value factor]{style="color: Tomato;"}.  Because the relation $y=x(1+r)^n$ is equivalent to 
$$x = \frac{y}{(1+r)^n},$$
we can also compute the present value $x$ from the future value $y$ by dividing by $(1+r)^n$ or, equivalently, by multiplying by $1/(1+r)^n$.  Consequently, we call $1/(1+r)^n$ the [present value factor]{style="color: Tomato;"} (or discount factor).  The operation of multiplying by the present value factor is called discounting, and the operation of multiplying by the future value factor is called compounding.  We also call the rate of return $r$ the discount rate.

To see why we should multiply the present value $x$ by the future value factor to obtain the future value, consider a concrete example, say $x=10$.  We can think of an investment account starting with $x=10$ as the sum of 10 hypothetical separate accounts, each starting with $1.  We saw earlier that $1 will grow to $(1+r)^n$ dollars in $n$ years when the rate of return is $r$.  At the end of the $n$ years, we can hypothetically consolidate the separate accounts, having a total of 10 times $(1+r)^n$; in other words, $x(1+r)^n$.

The values in  @fig-miracle-exponential are future value factors at 4% and 8%, for various $n$.   @fig-miracle-pvfactors presents the analogous present value factors.  Present value factors are smaller the further out in the future we look, and they are smaller when the discount rate is larger.

```{python}
#| label: fig-miracle-pvfactors
#| fig-cap: "Present Value Factors"


import plotly.graph_objects as go
import numpy as np

trace1= go.Scatter(
    x=np.arange(31), 
    y=1.08**(-np.arange(31)),
    mode="lines",
    name="8%"
)

trace2 = go.Scatter(
    x=np.arange(31), 
    y=1.04**(-np.arange(31)),
    mode="lines",
    name="4%"
)

fig = go.Figure()
fig.layout.template = "none"
fig.add_trace(trace1)
fig.add_trace(trace2)
fig.update_traces(
    hovertemplate="""
    Year %{x}<br>
    $%{y:.2f}<extra></extra>
    """
)
fig.layout.xaxis["title"] = "Year"
fig.layout.yaxis["title"] = "Present Value Factor"
fig.update_layout(
    yaxis_tickformat=".0%",
    legend=dict(
        yanchor="top", 
        y=0.99, 
        xanchor="right", 
        x=0.99
        )
)
fig.show()
```

::: callout-tip

# Future and present value factors

The numpy arange function is useful for creating sequences (arrays) of future value and present value factors.  
``` p
import numpy as np
n = 30
r = 0.08
fvFactors = (1+r)**np.arange(1, n+1)
pvFactors = (1+r)**np.arange(-1, -n-1, -1)
```
:::

## Multiple cash flows

Suppose we have some money $x_0$ to invest today, will have a possibly different amount $x_1$ to invest in one year, an amount $x_2$ to invest two years from now and so on for $m$ years, and we have an investment horizon of $n\ge m$ years.  How much will we have in $n$ years if we earn a return $r$ each year?  In other words, what is the total future value of the sequence of investments $x_0, \ldots, x_m$?

We can answer this question by treating our investment account as $m+1$ hypothetical separate accounts.  In the first account, we deposit $x_0$ today and it grows for $n$ years to $x_0(1+r)^n$.  In the second account, we deposit $x_1$ in one year and it grows for $n-1$ years to $x_1(1+r)^{n-1}$.  We can continue this through year $m$, and at the end of $n$ years, we can hypothetically consolidate the various accounts, producing a total future value of
$$x_0(1+r)^n + x_1(1+r)^{n-1} + x_2(1+r)^{n-2} + \cdots + 
x_m(1+r)^{n-m}.$$


::: callout-tip

# Future value of multiple cash flows

The total future value can be calculated by summing the product of two arrays as in the following example.  
``` p
import numpy as np
n = 10
m = 4
r = 0.08
x0, x1, x2, x3, x4 = 100, 120, 130, 140, 150
x = np.array([x0, x1, x2, x3, x4])
fvFactors = (1+r)**np.arange(n, n-m-1, -1)
total = np.sum(x*fvFactors)
```
:::

Now, consider the opposite question.  Suppose we want to spend some amount $y_1$ in one year, a possibly different amount $y_2$ in two years, and continuing for $m$ years.  If we want to finance all of these expenditures from a current investment account, how much do we need to have in the account now, assuming we always earn a return $r$ on the remaining balance?  The answer is that we need to have the total present value of the future values $y_1, y_2, \ldots, y_m$; that is, we need
$$\frac{y_1}{1+r} + \frac{y_2}{(1+r)^2} + \cdots + \frac{y_m}{(1+r)^m}.$$

::: callout-tip

# Present value of multiple cash flows

The total present value can also be computed by summing the product of two arrays as in the following example.  
``` p
import numpy as np
m = 4
r = 0.08
y1, y2, y3, y4 = 100, 120, 130, 140, 150
y = np.array([y1, y2, y3, y4])
pvFactors = (1+r)**np.arange(-1, -m-1, -1)
total = np.sum(y*pvFactors)
```
:::

Our examples here involved only positive cash flows, but it is also possible to compute total future values or total present values in this way when some cash flows are positive and some are negative.  In this case, the total present value is usually called the [net present value]{style="color: Tomato;"}, being the present value of the positive cash flows net of the present value of the negative cash flows.

## Perpetuities and annuities

An annuity is a level sequence of cash flows that extend for a finite period of time.  A perpetuity is a level sequence of cash flows that extend forever.  Annuities are encountered frequently, for example, in mortgage or other loan payments.  Perpetuities are encountered less often; however, studying them is still useful, in part because it leads to a simple valuation formula for annuities.

Suppose we want to spend $y$ in one year, another $y$ in two years, and so on forever.  How much do we need to have in an investment account today to finance all of these expenditures, if the account always earns $r$ per year?  The answer is the sum of the present values, which is
$$\frac{y}{1+r} + \frac{y}{(1+r)^2} + \frac{y}{(1+r)^3} + \cdots$$
The series of terms $y/(1+r)^n$ is a geometric series, and the present value is the sum of a geometric series, which by a standard formula equals
$$\frac{y/(1+r)}{1- 1/(1+r)} = \frac{y}{r}.$$
Thus, $y/r$ is the present value of a perpetuity of $y$ per year, given a rate of return of $r$ per year.
We can also reach this conclusion without using the formula for the sum of a geometric series.  If we start with $y/r$ in the account, then we will earn $r \times y/r=y$ in the first year, which we can spend without depleting our capital of $y/r$.  Clearly, we can continue this forever, so $y/r$ is exactly the amount we need to finance an expenditure of $y$ per year.

Now consider an annuity of $y$ per year for $n$ years.  The present value is
$$\frac{y}{1+r} + \frac{y}{(1+r)^2}  + \cdots + \frac{y}{(1+r)^n}$$
This annuity is the difference of two perpetuities: a perpetuity that starts in a year and another perpetuity that starts in $n+1$ years.  So, the present value is the difference of two present values: the present value $y/r$ of the first perpetuity minus the present value of the second perpetuity.  The present value of the second perpetuity as of year $n$ (one year before it begins) is $y/r$ and that value discounted to today is 
$$\frac{1}{(1+r)^n} \times \frac{y}{r}.$$
Hence, the present value of the annuity is
$$\frac{y}{r} - \frac{1}{(1+r)^n} \times \frac{y}{r} = \frac{y}{r} \left(1-\frac{1}{(1+r)^n}\right).$$

We call the following the [annuity factor]{style="color: Tomato;"}:
$$ \text{AF} = \frac{1}{r} \left(1-\frac{1}{(1+r)^n}\right).$$
The present value of the annuity is
$$ y \times \text{AF}.$$

::: callout-tip

# Calculating annuity values

Here are three ways to compute the present value of an annuity in python.  You may need to install the numpy_financial library ("pip install numpy-financial") for the third.  
``` p
import numpy as np
n = 10
y = 100
r = 0.08

# method 1
pvFactors = (1+r)**np.arange(-1, -n-1, -1)
pv = y * np.sum(pvFactors)

# method 2
AF = (1/r) * (1 - (1+r)**(-n))
pv = y * AF

# method 3
import numpy_financial as npf
pv = npf.pv(rate=r, nper=n, pmt=-y)
```
:::

We sometimes encounter finite or infinite sequences of cash flows that grow at a constant rate.  Consider a cash flow of $y$ in one year, $(1+g)y$ in two years, $(1+g)^2y$ in three years, etc., for some growth rate $g$. If the growing cash flows go on forever, then the present value is
$$\frac{y}{1+r} + \frac{(1+g)y}{(1+r)^2} + \frac{(1+g)^2y}{(1+r)^3} + \cdots$$
If $g \ge r$, meaning that growth in the cash flows is so fast that it offsets or more than offsets the discounting, then the terms in this series are constant or rising, so the sum is infinite.  If $g<r$, then the formula for the sum of a geometric series shows that the present value is
$$\frac{y/(1+r)}{1-(1+g)/(1+r)} =  \frac{y}{r-g}.$$
We can also see this by assuming that we start with $y/(r-g)$.  In the first year, we earn $ry/(r-g)$ from which we can spend $y$ and reinvest $ry/(r-g)-y =gy/(r-g)$, so our account will grow at rate $g$.  This growth is enough to finance a cash flow growing at rate $g$, and this can continue forever.  

If the sequence of growing cash flows lasts for a finite number $n$ of years, then it is a growing annuity, and its value is the difference of the values of two growing perpetuities.  Similar to the case of a level annuity, we can compute the value of a growing annuity as
$$\frac{y}{r-g} - \frac{1}{(1+r)^n} \times \frac{y}{r-g} = \frac{y}{r-g}\left(1 - \frac{1}{(1+r)^n}\right).$$

## Monthly rates, etc.

We frequently encounter rates of return, including interest rates, at frequencies other than a year, for example, when calculating monthly mortgage payments.  There are two ways of relating monthly rates to annual rates.  One is to compound monthly rates; the other is to multiply by 12.

First we address compounding.  Just as we calculated a future value by compounding an annual rate, we can also calculate a future value by compounding a monthly rate.  The future value of $1 in one year, with a monthly rate of $r_m$, is $(1+r_m)^{12}$.  The growth in value is
$$(1+r_m)^{12} - 1.$$
This is the annual rate of return obtained by monthly compounding at the monthly rate $r_m$.  For example, if the monthly rate is 1%, then the annual rate is
$$ r_a = (1+r_m)^{12} - 1 = 1.01^{12} - 1 = 0.1268.$$
So, a monthly rate of 1% compounds to 12.68% annually.  

We can reverse this calculation and compute the monthly rate given the annual rate.  The formula for the monthly rate is
$$r_m = (1+r_a)^{1/12} - 1.$$
If we plug in $r_a = 0.1268$, we'll get $r_m = 0.01$ (up to rounding error).  

This is a logical way to define monthly rates from annual rates, but it is not the way a bank does it when you take out a loan.  If a bank says that the annual rate is 12.68%, then it will charge you
$$\frac{0.1268}{12} = 0.0106.$$
So, the bank will charge you 1.06% monthly.  Obviously, this works in the bank's favor, relative to the calculation based on compounding.

Returning to the compounding calculation, we could also compound at frequencies other than a month or a year.  If we compound daily at a daily rate of $r_d$, then the corresponding annual rate is
$$r_a = (1+r_d)^{365} - 1.$$
The annual rate achieved by compounding is higher the more frequently a bank compounds.  Continuing with our previous example of 12.68%, with monthly compounding we have
$$\left(1 + \frac{0.1268}{12}\right)^{12} - 1 = 0.1344$$
and with daily compounding we have
$$\left(1 + \frac{0.1268}{365}\right)^{365} - 1 = 0.1351.$$
Thus, increasing the compounding frequency increases the corresponding annual rate.  We could consider even more frequent compounding.  In the limit, as compounding becomes continuous, we obtain
$$\lim_{n \rightarrow \infty}  \left(1 + \frac{0.1268}{n}\right)^{n} - 1  = e^{0.1268} - 1 = 0.1352,$$
where $e$ is the natural exponential ($2.718\ldots$).  Obviously, continuous compounding is never encountered in practice, but it is a useful "as if" device for some calculations that we will encounter later.

## Principal, payments, and rate

When buying a car or home, we might have one or more of the following questions.

1.  I know how much I want to borrow, what the term of the loan will be, and what the rate will be.  What will my payments be?
2.  I know what the term of the loan will be and what the rate will be, and I know the payment that I can afford.  How much can I borrow?
3.  I know what the term of the loan will be, how much I want to borrow, and how much I can afford to pay.  What rate do I need to get?

In this section, we will explain how to answer these questions.  For concreteness, suppose the loan will have monthly payments.  We will work in terms of an annual rate $r$ and calculate the monthly rate as $r/12$ the way banks do.  Analogous calculations can be used to answer the questions for loans with annual payments.

Our guiding principle is the formula for the present value of an annuity:
$$\text{PV} = y \times \text{AF}$$
where the annuity factor, with a monthly rate of $r/12$ and a term of $n$ years (so, $12n$ months), is
$$\text{AF} = \frac{1}{r/12}\left(1 - \frac{1}{(1+r/12)^{12n}}\right).$$
This formula applies to the given questions with PV equal to the loan amount and $y$ equal to the loan payment.  In other words, the relation between the loan amount and the loan payments is that the present value of the payments equals the loan amount (loan principal).  

The answers to the questions are as follows.  It is a bit more complicated to calculate the required rate than it is to calculate the payment and loan amount.

1.  The loan payment is the loan amount divided by the annuity factor.
2.  The loan amount is the loan payment multiplied by the annuity factor.
3.  The required rate is the rate that makes the annuity factor equal to the ratio of the loan amount to the loan payment.

::: callout-tip

# Calculating principals and payments

Here are ways to calculate a loan payment or loan amount.  
``` p
import numpy as np
n = 30     # number of years
r = 0.04   # annual rate

AF = (12/r) * (1 - (1+r/12)**(-12*n))

# calculate the loan payment
amount = 100000
payment = amount / AF

# calculate the loan amount
payment = 2000
amount = payment * AF
```
:::

Let's also answer a fourth question, which might occasionally arise:

4.  I know what the term of the loan will be, how much I want to borrow, how much I can afford to pay, and what the rate will be.  If my payments aren't enough, and I can get a balloon structure (a final payoff at maturity), how much will the balloon be?

If there is a balloon structure, then the loan amount equals the present value of the non-balloon payments ($\text{payment} \times \text{AF}$) plus the present value of the balloon, which is
$$\text{balloon} \times \frac{1}{(1+r/12)^{12n}}.$$
Thus,
$$\text{balloon} = \left(1+\frac{r}{12}\right)^{12n} \times (\text{amount} - \text{payment} \times AF)$$
This is the future value of the present value "shortage;" that is, it is the future value of the loan amount in excess of the present value of the monthly payments.  

::: callout-tip

# Using numpy-financial

Here are the answers to all four questions, using functions from numpy-financial.  The sign conventions are that the loan amount is positive (a cash inflow) and loan payments (regular payments and balloon) are negative.  If the balloon calculation turns out to be positive, it means we've overpaid the bank and should get money back.  We can include a balloon when answering the first three questions by setting, for example, **fv=-100000** when the balloon is $100,000.
``` p
import numpy_financial as npf
n = 30     # number of years

# question 1
r = 0.04
amount = 500000
payment = npf.pmt(
    rate=r/12,
    nper=n*12,
    pv=amount, 
    fv=0
)

# question 2
r = 0.04
payment = -2000
amount = npf.pv(
    rate=r/12,
    nper=n*12,
    pmt=payment,
    fv=0
)

# question 3
amount = 500000
payment = -2000
rate = 12*npf.rate(
    nper=n*12,
    pv=amount,
    pmt=payment,
    fv=0
)

# question 4
r = 0.04
amount = 500000
payment = -2000
balloon = npf.fv(
    rate=r/12,
    nper=n*12,
    pmt=payment,
    pv=amount
)

```
:::


## Inflation and real returns

In the decade 1971--1980, the U.S. stock market returned an average of 9.2% per year.  A dollar invested at the first of January in 1971 would have grown to $2.40 by the end of December in 1980.  As decades go, this is quite far from the worst for the U.S. stock market.^[Of the nine decades, 1931-1940, ..., 2011-2020, it ranks fifth.]  However, the 1970's were a time of high inflation.  What was the market performance in real terms?  To be more precise, if we had invested $1 at the begining of January, 1971, by how much would our real buying power have grown by the end of December, 1980?  In other words, what was our return in constant dollars?  We will see here how to answer these questions.

The standard measurement of the inflation rate is the percent change in a price index.  In the U.S., the standard price index used for this calculation is the Consumer Price Index -- All Urban calculated by the Bureau of Labor Statistics.  It represents the cost of a basket of goods sampled in 87 urban areas across the U.S.  To have 7% inflation in a year means that the basket of goods costs 7% more at the end of the year than at the beginning, or in other words that
$$\frac{\text{CPI at end of year}}{\text{CPI at beginning of year}} = 1.07.$$

Consider an item that costs $100 today.  Suppose there is 7\% inflation in the coming year, and the item costs $107 at the end of the year.  Suppose also that our portfolio earns 20\% in the year.  To calculate our real return, consider each $100 that we have at the start of the year.  Each $100 could buy one item.  In a year's time, the $100 grows to $120, and the item costs $107, so we could buy one and have $13 left over, which would buy 13/107 units.  This 13/107 is the growth in our buying power relative to the start of the year, so our [real return]{style="color: Tomato"} is 13/107.  

We can express the calculation in the previous paragraph in more generality as
$$\text{real return} = \frac{\text{nominal return} - \text{inflation rate}}{1 + \text{inflation rate}},$$
where the nominal return is the return before adjustment for inflation (20\% in our example) and all returns and rates are in decimal form.  We also call the real return the [return in constant dollars]{style="color: Tomato"}.




We can compound real returns the same way we compounded returns earlier.  Let $r$ denote the real return, $i$ denote the inflation rate, and $z$ denote the nominal return (all in decimal form).  Adding 1 to both sides of the equation for the real return gives
$$1+r = \frac{z-i}{1+i} + 1 = \frac{1+z}{1+i}.$$
To calculate what $1 grows to in constant dollars over a period of $n$ years, we calculate 
$$(1+r_1)(1+r_2) \cdots (1+r_n)$$ where the $r_i$ are the real returns.  By the above formula,
$$(1+r_1) \cdots (1+r_n) = \frac{(1+z_1) \cdots (1+z_n)}{(1+i_1) \cdots (1+i_n)}.$$
The numerator on the right hand side is what $1 grows to in nominal dollars.  The denominator is the growth in the price index.  To be specific, the denominator is
$$\frac{\text{CPI at end of year $n$}}{\text{CPI at beginning of year 1}}.$$
Thus, the real return over a period of years equals the nominal return over the period with the growth in the CPI divided out.

To come back to our example -- over the decade 1971--1980, \$1 invested in the U.S. stock market grew to \$2.40 in nominal terms, as stated earlier.  However, the CPI at the end of the decade was 2.3 times its value at the beginning of the decade.  In other words, compounded inflation $(1+i_1) \cdots (1+i_n)$ over the decade was 2.3.  So, the dollar grew to only 2.40 / 2.30 = 1.04 dollars in real terms, meaning that the total real return over the decade was only 4%.  So, it was a middling decade in nominal terms and a very poor decade in real terms.

## Geometric average returns

The actual returns of the U.S. market over the decade 1971--1980 were

* 1971 = 16.17\%
* 1972 = 16.89\%
* 1973 = -19.25%
* 1974 = -27.75%
* 1975 = 38.24%
* 1976 = 26.99%
* 1977 = -3.14%
* 1978 = 8.21%
* 1979 = 23.47%
* 1980 = 33.37%

The average of these ten numbers is 11.32%.  So, why did we say in the previous section that the market averaged 9.2% in the decade?  The reason is that, if we had been invested throughout the decade, our return would have been exactly the same as if we earned 9.2\% per year; that is,
$$(1+r_{\text{1971}}) \cdots (1+r_{\text{1980}}) = 2.40 = 1.092^{10}.$$
However, we should have been more precise in our language.  The correct thing to say is that the [geometric average]{style="color: Tomato"} return in the decade was 9.2%.  The general definition of the geometric average of a sequence of returns $r_1, \ldots, r_n$ is that it is the number $r$ such that
$$(1+r_1) \cdots (1+r_n) = (1+r)^n.$$
In other words, $1 grows to the same amount in an account that earns the returns $r_1, \ldots, r_n$ as it does when earning $r$ every year. 
When there is a risk of confusion, we will call the usual average (0.01132 for 1971--1980) the [arithmetic average]{style="color: Tomato"} return.  Both averages have their uses, as we will see in subsequent chapters.

If there is any variability in the returns from period to period, then the geometric average is smaller than the arithmetic average, and the difference between the two is larger when returns are more variable.  The substantial variability in the 1970's produced the more than 2\% difference between the two for that decade.  

For a simpler example of the difference between the two averages, suppose an asset falls 50% in one year and then gains 50% the next.  The arithmetic average is zero, but the asset is actually down 25\%.  If it started at $100, it fell to $50 and then recovered only to $75.  To find the geometric average, we solve
$$(1+r)^2 = (1 - 0.5)(1 + 0.5) = 0.75,$$
which is equivalent to
$$r = \sqrt{0.75} - 1 = - 0.134.$$
Losing 13.4% two years in a year will put us 25% down.  In general, the geometric average is computed as
$$r = [(1+r_1) \cdots (1+r_n)]^{1/n}.$$
To continue the example, to get back to even after losing 50\%, clearly an asset needs to double, meaning a 100% return.  The geometric average would be zero, and the arithmetic average would be 25%.  The large difference between the two is due to the extremely high variability in this example.

::: callout-note
## Geometric averages and continuously compounded returns

The term "geometric average" is not unique to finance, but it is used a little differently in finance than elsewhere.  Using the term in its non-finance meaning, the relationship
 $$(1+r)^n = (1+r_1) \cdots (1+r_n)$$
 would be described by saying that $1+r$ is the geometric average of the $1+r_1, \ldots, 1+r_n$.
This is a little cumbersome to say, so in finance we simply say that $r$ is the geometric average of the $r_i$.  To see in what sense this relationship represents an average, take the natural logarithm of both sides.  This produces
$$n \log (1+r) = \log (1+r_1) + \cdots \log (1+r_n)$$
or, equivalently,
$$\log (1+r) = \frac{\log (1+r_1) + \cdots + \log (1+r_n)}{n}.$$
Thus, "geometric average" means "average in logs."  These logarithms of one-plus-returns are called continuously compounded returns.  Recall that if \$1 is invested for a year with continuous compounding, then it grows to $e^z$, where $e$ is the natural exponential.  So, by investing \$1 for a year at rate $\log (1+r)$ with continuous compounding , at the end of the year we have $e^{\log (1+r)} = 1+r$.  Therefore, continuous compounding at rate $\log (1+r)$ is the same as earning $r$.  The upshot is that "geometric average" means a normal (arithmetic) average for continuously compounded returns.  Returning to the earlier example, suppose an asset drops by 50\% and then has a 100\% return, getting back to even.  The continuously compounded returns are $\log (1-0.5) = \log 0.5$ and $\log (1+1) = \log 2$, and it is indeed true that $\log 0.5 + \log 2 = 0$, so the average continuously compounded return represents the true experience of the asset -- it broke even.
:::

## Retirement planning




::: callout-note
## A title for a note
This is a highlighted block of text.
:::


::: callout-important
## A title for something important
Something important goes here
:::

::: callout-warning
## A title for a warning

Some warning goes here
:::

::: callout
## A simple title

Anything could go here
::: 

``` p
# this is a displayed code block

import numpy as np
x = np.arange(4)
```



